### PR TITLE
Move maxChatToKeep to the config file.

### PR DESCRIPTION
**Pull request by hjstn**
Moving modifiable values to the config files would be better for the user than to poke around the files and then editing them.

### CODE REVIEW

**Comment by Dinnerbone** [comment]
I'm thinking that we won't actually use it here, but make each plugin (that cares about it) responsible for tracking it themselves. Then it can be configured per plugin a bit more naturally ("how many duplicate lines before kick" vs "how many lines to remember for unknown purposes")

**Comment by hjstn** [comment]
Separate config files for each plugin? Or sort them all in config.json like `{ plugins: { users: {maxChatToKeep: 3 } } }`?

**Comment by Dinnerbone** [comment]
It already supports them in config.json exactly like that, where `users` is the name of the plugin.

**Comment by hjstn** [comment]
Ah, alright, I'll make another PR for that, then.

**Comment by Dinnerbone** [comment]
We don't actually have anything that uses the chat history yet, so I'd wait until then! :D

**Pull request closed without merging**
